import mongoose, { Schema } from "mongoose";

// This collection is intentionally independent from `Customization`.  It only
// contains the snapshot uploaded by an offline/desktop installation.
const offlineReportSchema = new mongoose.Schema({
    tenantId: { type: mongoose.Types.ObjectId, ref: "User" },
    createdBy: { type: mongoose.Types.ObjectId, ref: "User" },
    bookingId: { type: String, default: "" },
    DownloadPdf: { type: Boolean, default: false },
    showInvest: { type: Boolean, default: true },
    BoldRow: { type: Boolean, default: true },
    HLinred: { type: Boolean, default: false },
    HighLow: { type: Boolean, default: true },
    RowSpacing: { type: Number, default: 7 },
    selectedFontSize: { type: Number, default: 12 },
    selectedFontFamily: { type: String, default: "Arial" },
    hideCategories: { type: Boolean, default: false },
    hideTableHeadings: { type: Boolean, default: false },
    reportId: { type: Schema.Types.ObjectId },
    htmlContent: { type: String, default: "" },
    cssContent: { type: String, default: "" },
    header: { type: String, default: "" },
    footer: { type: String, default: "" },
    backgroundImageUrl: { type: String, default: "" },
    backgroundImage: { type: String, default: "" },
    bgImage: { type: String, default: "" },
    backgroundImg: { type: String, default: "" },
    imageUrl: { type: String, default: "" },
    templateImage: { type: String, default: "" },
    template: { type: String, default: "" },
    background: { type: String, default: "" },
    headermargin: { type: String, default: "2.8" },
    footermargin: { type: String, default: "1" },
    marginRight: { type: String, default: "0" },
    marginLeft: { type: String, default: "0" },
    LeftsignPd: { type: String, default: "0" },
    Rightsignpd: { type: String, default: "0" },
    investigationmargin: { type: Number, default: 1 },
    showlab: { type: Boolean, default: false },
    showdoctorfirst: { type: Boolean, default: true },
    showdoctorsecond: { type: Boolean, default: true },
    fileInputLab: { type: String, default: "" },
    fileInputDoctorleft: { type: String, default: "" },
    fileInputDoctorright: { type: String, default: "" },
    fileInputLabtext: { type: String, default: "" },
    fileInputDoctorlefttext: { type: String, default: "" },
    fileInputDoctorrighttext: { type: String, default: "" },
    isdocumented: { type: Boolean, default: false },
    checkBox: { type: Boolean, default: false },
    disableBackgroundImage: { type: Boolean, default: false },
    // Not part of Customization, but needed to reproduce the offline layout.
    pdfFormat: { type: String, default: "reportFormat1" },

    // Stable ID supplied by the offline MongoDB. It avoids depending on an
    // ObjectId generated by this cloud database.
    offlineReportId: { type: String, required: true, unique: true, trim: true, index: true },
    downloadToken: { type: String, required: true, unique: true, index: true, select: false },
    expiresAt: { type: Date, required: true },
}, { timestamps: true, collection: "offline_reports" });

offlineReportSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
offlineReportSchema.index({ reportId: 1 });
offlineReportSchema.index({ tenantId: 1, createdBy: 1, reportId: 1 });

const OfflineReport = mongoose.model("OfflineReport", offlineReportSchema);

export { OfflineReport };
